moderators:
  # Core Team
  - "NDkyOTc4NzU5OTE4NDE5OTc4" # Kamil
  - "NTI0MjgxOTIxMTE1NjUyMTA2" # jmcdo29
  - "MjI1ODU4OTgzNjMyNjk5Mzky" # Brunner Livio
  - "NTE3MTcwNTk4ODMzNTUzNDA4" # Y Prospect
  - "MTMyMjIyMTg5MjA5NTE4MDgw" # Micael (micalevisk)
  - "NTcwMzU0NjAyMDYzNjkxODI2" # markpieszak

  # Community Mods
  - "MTE4NjMzNDA4NDM4OTkyODk2" # wodCZ
  - "NjQ2MTA3NDUzNDY5MjI5MDU2" # Papooch
  - "MjY3NjYxNjQ3Nzg1NjIzNTcy" # Scott
  - "MzcwOTAzNzAwOTc5MzE4Nzg0" # Script
  - "NzE4NTM4MTQ3NDQ5MDEyMjQ1" # Tony
  - "MjEwOTg0NDMzMzIxMjQ2NzIw" # underfisk
  - "NjczNjU4NzI4ODYzNjI5MzYw" # Maciej Sikorski (Matthew)

  # MVPs
  - "MjExNDQ1Njc1NzAxODI5NjMy" # weshuiz13

rateLimit: # only applies to the application commands
  ttlSec: 60
  maxUsage: 8
  message: >
    Chill out, cowboy!
    You don't want to overload our poor server.

antispam: # flags the users who spam messages on multiple channels in a short timeframe.
  enabled: true
  logChannelId: "918987870197395577" # TODO: migrate to the "auto mod messages" channel
  moderatorsBypass: true
  messageTTLSec: 60 # how long the messages should be kept in the memory.
  maxChannelsPerUser: 3 # the maximum number of channels a user can send messages in within the defined TTL timeframe.
  denyTTLSec: 120 # how long a spammer user ID should be kept in the memory (to delete their future messages).
  trackedChannelIds:
    # Information (read-only)
    # - "527853342152458287" # welcome
    # - "525389275769077771" # resources
    # - "669488633228558339" # roles
    # - "669642626001010709" # partners

    # Core Team (private)
    # - "808120635682586644" # moderator-mvp-exchange
    # - "918987870197395577" # bot-test
    # - "1028324313180413982" # auto mod messages
    # - "1294488503744204860" # mod-profiles
    # - "1294488539500777472" # mod-opportunities
    # - "598294041150619662" # marketing
    # - "523471550104731659" # general (archived)
    # - "613075872915783682" # core-team-devops (archived)

    # Community Modules
    - "626341204442742784" # community-packages

    # Community
    - "523472945205608454" # showcase
    - "523473854694424576" # media
    - "585224763513765937" # hangout
    - "679231901109714945" # share-your-pet

    # Development
    - "939229065527820369" # contributing-to-nest
    # - "610578507579392153" # code-review (read-only)

    # Languages
    - "810948706902736918" # German
    - "744635201690533956" # Spanish
    - "810948689295048714" # French
    - "810948655846260766" # Polish
    - "811732928517767179" # Portuguese
    - "815841356894306304" # Russian
    - "1208424317285830686" # Romanian
    - "975075877274660865" # Turkish
    - "934100953324466186" # Korean
    - "1068390891489874010" # Korean
    - "1099202167484719194" # Persian
    - "1155462622251073656" # Arabic

    # Discord
    - "524255662545305600" # server-suggestions

    # Bots
    # - "926544704034734111" # bots-info (read-only)
    - "926544725606035527" # bot-commands

# Text input documentation:
# https://discord.com/developers/docs/interactions/message-components#text-inputs
#
# If the destination of the form submission (form.foo.channelId) is an announcement channel,
# ensure the bot *explicitly* has the following permissions:
#   - Send Messages
#   - Manage Messages
#   - Read Message History
# Otherwise, the bot will panic and the container will enter a restart loop.
# More details on announcement channels:
# https://support.discord.com/hc/en-us/articles/360032008192-Announcement-Channels
forms:
  job-profiles: # Self-promotion
    buttonLabel: "Post a new profile"
    modalTitle: "Post a new profile"
    channelId: 1294483543623335986 # prod: 1294483543623335986 | dev: 1294446757370925147
    modChannelId: 1294488503744204860 # prod: 1294488503744204860 | dev: 1292911145883275356
    modSkipApproval: false
    color: 2600544 # dark green (#27ae60)
    footer: "Details of this profile have not been verified, please do your own due diligence."
    inputs:
      - id: "about"
        placeholder: "Shortly describe yourself!"
        multiline: false
        min: 15
        max: 100
        required: true
      - id: "skills"
        placeholder: "NestJS, Node.js, TypeScript, Golang, ..."
        multiline: true
        min: 2
        max: 400
        required: true
      - id: "experiences"
        placeholder: "Use bullet points (-) for better formatting."
        multiline: true
        min: 2
        max: 600
      - id: "location"
        placeholder: "Germany, Berlin - Remote, On-site in Mitte, willing to relocate within Europe"
        min: 2
        max: 150
        required: true
        multiline: false
      - id: "links"
        placeholder: "https://github.com/foo/bar\nhttps://your.personal-website.com/"
        min: 0
        max: 200
        required: false
        multiline: true

  job-opportunities: # Job listing
    buttonLabel: "Post a new opportunity"
    modalTitle: "Post a new opportunity"
    channelId: 1294483759189725265 # prod: 1294483759189725265 | dev: 1294446864036528231
    modChannelId: 1294488539500777472 # prod: 1294488539500777472 | dev: 1292911220197953558
    modSkipApproval: false
    color: 14689102 # same as the official nestjs logo (#e0234e)
    footer: "Details of this opportunity have not been verified, please do your own due diligence."
    inputs:
      - id: "title"
        placeholder: "Senior Software Engineer"
        min: 10
        max: 100
        required: true
        multiline: false
      - id: "compensation"
        placeholder: "$50 per hour"
        min: 5
        max: 100
        required: true
        multiline: false
      - id: "location"
        placeholder: "Germany, Berlin - Remote, On-site in Mitte, willing to relocate within Europe"
        min: 5
        max: 150
        required: true
        multiline: false
      - id: "description"
        placeholder: "We are seeking an engineer to assist with back-end development and server management."
        min: 50
        max: 1000
        required: true
        multiline: true
      - id: "links"
        placeholder: "https://company.com/jobs\nhttps://github.com/organization"
        min: 10
        max: 200
        required: true
        multiline: true


archiveCommand:
  response: > # TODO: make sure to use this key
    This post has been marked as archived.
    Please use it as a reference, but do not re-open it.
    If you have a similar issue and cannot resolve it after reading this thread, please open a new post.

solvedCommand:
  description: "Close and mark a forum post as solved."
  response: > # TODO: can the unnecessary next line characters be removed from here somehow?
    This post has been marked as resolved. ✅
    Please read through the conversation and resolution, if you are having the same issue.
    If you were the original author of the post and the issue is still fresh (within a few days)
    and you are still have having trouble, continue to reply here. If you are not the original
    author of the post or the post has aged, start a new thread linking this one as relevant to
    your problem, providing as much additional information as possible.
  # Map of the forum channel IDs against their "✅ solved" tag ID
  # This should speed up the command's response time by avoid Discord API calls.
  solvedTags: # TODO: fill the values
    123: "123"

  # For each command, use a key to define the command name.
  # If a key contains a single space character, it becomes a sub-command.
  #
  #   example sub-command:
  #     description: "This is my command"
  #     content: "And this is my awesome respond! 😎"
  #     protected: false
  #     buttons:
  #       -
  #         - label: "Button 1"
  #           url: "https://button1.com/"
  #           emoji: "🔗"
  #         - label: "Button 2"
  #           url: "https://button2.com/"
  #           emoji: "🔗"
  #
  # The properties for each command are as follows:
  #
  #   description (required, max 100 characters):
  #     A short description of the command.
  #
  #   content (required, max 3000 characters):
  #     What will be the response of this command when executed.
  #
  #   protected (optional, default is false):
  #     If set to true, only moderators will be able to see and use this command.
  #
  #   buttons (optional, max eight rows and four columns):
  #     An array of arrays representing rows and columns of Discord message components, specifically link buttons.
  #     Each link button has label, url, and an optional emoji string field.
  #     See https://discord.com/developers/docs/interactions/message-components for more information on message components.
commands:
  #
  # Moderator commands (hidden from the public users)
  #
  mods cross-post:
    description: "Warn users not to cross-post, ask in relevant channels, and be patient."
    protected: true
    content: "./content/mods/cross-post.md"

  mods spam:
    description: "A friendly warning to prevent spamming in the chat"
    protected: true
    content: "./content/mods/spam.md"

  mods elaborate:
    description: "Please provide more context so we can better assist you with your inquiry."
    content: "./content/mods/elaborate.md"
    buttons:
      - - label: "What is a reproduction repository?"
          url: "https://minimum-reproduction.wtf/"
          emoji: "🔗"

  #
  # Public commands (visible to all users)
  #
  community awesome:
    description: "A curated list of awesome things related to NestJS"
    content: "./content/community/awesome.md"
    buttons:
      - - label: "View repository on GitHub"
          url: "https://github.com/nestjs/awesome-nestjs"
          emoji: "🔗"

  community testing:
    description: "A GitHub repository to show off to the community methods of testing NestJS"
    content: "./content/community/testing.md"
    buttons:
      - - label: "View repository on GitHub"
          url: "https://github.com/jmcdo29/testing-nestjs"
          emoji: "🔗"

  docs behind-proxy:
    description: "How to enable the trust proxy option when NestJS app is behind a reverse proxy"
    content: "./content/docs/behind-proxy.md"
    buttons:
      - - label: "Express trust proxy docs"
          url: "https://expressjs.com/en/guide/behind-proxies.html"
          emoji: "🔗"
        - label: "Fastify trustProxy docs"
          url: "https://fastify.dev/docs/latest/Reference/Server#trustproxy"
          emoji: "🔗"
      - - label: "@nestjs/throttler docs"
          url: "https://docs.nestjs.com/security/rate-limiting#proxies"
          emoji: "📖"

  docs circular-dependency:
    description: "Circular dependencies in NestJS and how to avoid them"
    content: "./content/docs/circular-dependency.md"
    buttons:
      - - label: "Read rest of the documentation"
          url: "https://docs.nestjs.com/fundamentals/circular-dependency"
          emoji: "📖"
      - - label: "How to avoid circular dependencies"
          url: "https://trilon.io/blog/avoiding-circular-dependencies-in-nestjs"
          emoji: "📝"

  docs file-change-detected:
    description: "How to fix when TypeScript 4.9+ on Windows causes infinite loop in watch mode"
    content: "./content/docs/file-change-detected.md"
    buttons:
      - - label: "TypeScript documentation"
          url: "https://www.typescriptlang.org/tsconfig#watch-watchDirectory"
          emoji: "🔗"
      - - label: "New strategy for detecting file changes"
          url: "https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/#file-watching-now-uses-file-system-events"
          emoji: "📝"

  docs hybrid-app:
    description: "Create hybrid apps with NestJS and microservices"
    content: "./content/docs/hybrid-app.md"
    buttons:
      - - label: "Read more"
          url: "https://docs.nestjs.com/faq/hybrid-application"
          emoji: "📖"

  docs nest-debug:
    description: "Debug NestJS dependencies with environment variable"
    content: "./content/docs/nest-debug.md"

  docs process-env-population:
    description: "What to do when process.env is not populated"
    content: "./content/docs/process-env-population.md"
    buttons:
      - - label: "How to use the ConfigService"
          url: "https://docs.nestjs.com/techniques/configuration#using-the-configservice"
          emoji: "📖"

  docs providers-vs-imports:
    description: "Ensure accurate service/module listings"
    content: "./content/docs/providers-vs-imports.md"
    buttons:
      - - label: "Read more"
          url: "https://docs.nestjs.com/faq/common-errors#cannot-resolve-dependency-error"
          emoji: "📖"

  docs request-lifecycle:
    description: "Get a grip on NestJS' request lifecycle for smooth coding"
    content: "./content/docs/request-lifecycle.md"
    buttons:
      - - label: "Documentation reference"
          url: "https://docs.nestjs.com/faq/request-lifecycle"
          emoji: "🔗"

  docs resolve-dependencies:
    description: "Nest not being able to resolve dependencies of something"
    content: "./content/docs/resolve-dependencies.md"
    buttons:
      - - label: "Read more about this error"
          url: "https://docs.nestjs.com/faq/common-errors#cannot-resolve-dependency-error"
          emoji: "📖"
      - - label: "Standard NestJS provider practices"
          url: "https://docs.nestjs.com/fundamentals/custom-providers#di-fundamentals"
          emoji: "🔗"
      - - label: "Circular dependency"
          url: "https://docs.nestjs.com/faq/common-errors#circular-dependency-error"
          emoji: "🔗"
        - label: "Custom providers"
          url: "https://docs.nestjs.com/fundamentals/custom-providers"
          emoji: "🔗"

  rules codeblocks:
    description: "Letting people know how to share their code in a Markdown code block"
    content: "./content/rules/codeblocks.md"

  rules dm:
    description: "Use server to get help on NestJS; don't DM other members."
    content: "./content/rules/dm.md"

  rules dont-ask-to-ask:
    description: "Telling people to just ask their question with a link explaining why"
    content: "./content/rules/dont-ask-to-ask.md"
    buttons:
      - - label: "Learn more about asking to ask"
          url: "https://dontasktoask.com"
          emoji: "❓"

  rules no-hello:
    description: "Telling people not to say just 'hello' in the chat"
    content: "./content/rules/no-hello.md"
    buttons:
      - - label: "Why is this a thing"
          url: "https://nohello.net/en/"
          emoji: "❓"

  rules reproduction:
    description: "Request for a minimum reproduction of the issue"
    content: "./content/rules/reproduction.md"
    buttons:
      - - label: "Learn more about minimum reproductions"
          url: "https://minimum-reproduction.wtf"
          emoji: "📖"
      - - label: "SO Minimum Reproduction Description"
          url: "https://stackoverflow.com/help/minimal-reproducible-example"
          emoji: "🔗"

  rules screenshot:
    description: "When someone posts a screenshot instead of sharing their code"
    content: "./content/rules/screenshot.md"
    buttons:
      - - label: "Learn more about code-blocks"
          url: "https://discord.com/channels/520622812742811698/527853342152458287/935939213512298576"
          emoji: "🔗"

  javascript floating-promise:
    description: "Introduction to floating Promises in JavaScript"
    content: "./content/javascript/floating-promise.md"
    buttons:
      - - label: "Learn more about Promises, async/await"
          url: "https://javascript.info/async"
          emoji: "📖"
      - - label: "Eslint rule to prevent async code errors"
          url: "https://typescript-eslint.io/rules/no-floating-promises/"
          emoji: "🔗"

  request-info:
    description: "Ask them to run the \"npx @nestjs/cli info\" and paste the output in a code block."
    content: "./content/request-info.md"
    buttons:
      - - label: "Learn more about code-blocks"
          url: "https://discord.com/channels/520622812742811698/527853342152458287/935939213512298576"
          emoji: "🔗"

  show-the-error:
    description: "Telling people to be specific when seeking help. Share errors, and provide the code if possible."
    content: "./content/show-the-error.md"
    buttons:
      - - label: "Learn more about code-blocks"
          url: "https://discord.com/channels/520622812742811698/527853342152458287/935939213512298576"
          emoji: "🔗"
