version: "3.9"

services:
  utility-bot:
    container_name: nestjs-discord-utility-bot
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
      target: build-release-stage
#    entrypoint: ["/utility-bot", "discord:run", "--debug"]
    volumes: # in case, we may add the hot-reloading feature
      - ./content:/content:ro
      - ./config.yml:/config.yml:ro
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://127.0.0.1:2112/metrics" ]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 3s
    env_file:
      - .env
