# version: "3.9"

services:
#  redis:
#    image: redis:7.4.1-alpine
#    restart: unless-stopped
#    healthcheck:
#      test: [ "CMD", "redis-cli","ping" ]
#    ports:
#      - "127.0.0.1:6379:6379"

  bot:
    restart: unless-stopped
#    depends_on:
#      - redis
    build:
      context: ./
      dockerfile: Dockerfile
      target: production-stage
    volumes:
      - ./content:/usr/app/content:ro # TODO: remove (after removing the *.md files)
      - ./config.yml:/usr/app/config.yml:ro
    environment:
      DISCORD_APP_ID: "${DISCORD_APP_ID}"
      DISCORD_BOT_TOKEN: "${DISCORD_BOT_TOKEN}"
      DISCORD_GUILD_ID: "${DISCORD_GUILD_ID}"
