version: "3.9"

services:
  utility-bot:
    container_name: nestjs-discord-utility-bot
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
      target: production-stage # Multi-stage Docker build
    volumes: # In case, we may add the live-reloading feature
      - ./content:/usr/app/content:ro
      - ./config.yml:/usr/app/config.yml:ro
    environment:
      DISCORD_APP_ID: "${DISCORD_APP_ID}"
      DISCORD_BOT_TOKEN: "${DISCORD_BOT_TOKEN}"
      DISCORD_GUILD_ID: "${DISCORD_GUILD_ID}"

    # Bind prometheus metrics to host machine
    # http://127.0.0.1:2112/metrics
    # ports:
    #   - "127.0.0.1:2112:2112"

    # Sets log level to debug
    # entrypoint: ["ub", "discord:run", "--debug"]
