// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/nestjs-discord/utility-bot/app"
	"github.com/nestjs-discord/utility-bot/bot"
	"github.com/nestjs-discord/utility-bot/bot/antispam"
	"github.com/nestjs-discord/utility-bot/bot/auto_mod"
	"github.com/nestjs-discord/utility-bot/bot/commands"
	"github.com/nestjs-discord/utility-bot/bot/commands/archive"
	"github.com/nestjs-discord/utility-bot/bot/commands/credits"
	"github.com/nestjs-discord/utility-bot/bot/commands/dont_ping_mods"
	"github.com/nestjs-discord/utility-bot/bot/commands/google_it"
	"github.com/nestjs-discord/utility-bot/bot/commands/reference"
	"github.com/nestjs-discord/utility-bot/bot/commands/solved"
	"github.com/nestjs-discord/utility-bot/bot/forms"
	"github.com/nestjs-discord/utility-bot/bot/handler"
	"github.com/nestjs-discord/utility-bot/bot/handler/interaction"
	"github.com/nestjs-discord/utility-bot/bot/markdown"
	"github.com/nestjs-discord/utility-bot/bot/moderators"
	"github.com/nestjs-discord/utility-bot/bot/rate_limit"
	"github.com/nestjs-discord/utility-bot/bot/session"
	"github.com/nestjs-discord/utility-bot/bot/status"
	"github.com/nestjs-discord/utility-bot/infra/config/env"
	"github.com/nestjs-discord/utility-bot/infra/config/yaml"
	"github.com/nestjs-discord/utility-bot/infra/logger"
	"github.com/nestjs-discord/utility-bot/modules/cron"
)

// Injectors from wire.go:

func InitializeApp() (*app.App, func(), error) {
	discordConfig, err := env.NewDiscordConfig()
	if err != nil {
		return nil, nil, err
	}
	stage, err := env.NewStageConfig()
	if err != nil {
		return nil, nil, err
	}
	loggerLogger, err := logger.NewLogger(stage)
	if err != nil {
		return nil, nil, err
	}
	botBot, cleanup, err := bot.NewBot(discordConfig, loggerLogger)
	if err != nil {
		return nil, nil, err
	}
	sessionSession := bot.ProvideSession(botBot)
	path := _wirePathValue
	config, err := yaml.NewConfig(path)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	yamlForms := yaml.NewForms(config)
	discordgoSession := session.ProvideSession(sessionSession)
	guildId := env.ProvideGuildId(discordConfig)
	options := auto_mod.Options{
		Session: discordgoSession,
		GuildId: guildId,
	}
	autoMod, err := auto_mod.NewAutoMod(options)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	yamlCommands := yaml.NewCommands(config)
	markdownOptions := markdown.Options{
		Commands: yamlCommands,
	}
	markdownMarkdown := markdown.NewMarkdown(markdownOptions)
	formsOptions := forms.Options{
		Cfg:      yamlForms,
		AutoMod:  autoMod,
		Markdown: markdownMarkdown,
		Session:  discordgoSession,
	}
	formsForms, err := forms.NewForms(formsOptions)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	yamlModerators := yaml.NewModerators(config)
	moderatorsOptions := moderators.Options{
		EncodedUserIds: yamlModerators,
	}
	moderatorsModerators, err := moderators.NewModerators(moderatorsOptions)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	rateLimit := yaml.NewRateLimit(config)
	rate_limitOptions := rate_limit.Options{
		Cfg:        rateLimit,
		Moderators: moderatorsModerators,
	}
	rate_limitRateLimit := rate_limit.NewRateLimit(rate_limitOptions)
	archiveCommand := yaml.NewArchiveCommand(config)
	archiveArchive := archive.NewArchive(archiveCommand, moderatorsModerators)
	creditsCredits := credits.NewCredits()
	googleIt := google_it.NewGoogleIt()
	referenceReference := reference.NewReference()
	solvedCommand := yaml.NewSolvedCommand(config)
	solvedOptions := solved.Options{
		Cfg:        solvedCommand,
		Moderators: moderatorsModerators,
	}
	solvedSolved := solved.NewSolved(solvedOptions)
	dontPingMods := dont_ping_mods.NewDontPingMods(moderatorsModerators)
	interactionOptions := interaction.Options{
		Forms:        formsForms,
		Moderators:   moderatorsModerators,
		RateLimit:    rate_limitRateLimit,
		Markdown:     markdownMarkdown,
		Archive:      archiveArchive,
		Credits:      creditsCredits,
		GoogleIt:     googleIt,
		Reference:    referenceReference,
		Solved:       solvedSolved,
		DontPingMods: dontPingMods,
	}
	interactionHandler := interaction.NewInteractionHandler(interactionOptions)
	yamlAntispam := yaml.NewAntispam(config)
	antispamOptions := antispam.Options{
		Cfg:        yamlAntispam,
		Moderators: moderatorsModerators,
	}
	antispamAntispam, err := antispam.NewAntispam(antispamOptions)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	handlerOptions := handler.Options{
		InteractionHandler: interactionHandler,
		Antispam:           antispamAntispam,
		Forms:              formsForms,
		Markdown:           markdownMarkdown,
		Moderators:         moderatorsModerators,
	}
	handlerHandler := handler.NewHandler(handlerOptions)
	statusOptions := status.Options{
		Session: discordgoSession,
	}
	statusStatus := status.NewStatus(statusOptions)
	option := cron.Option{
		AutoMod: autoMod,
		Status:  statusStatus,
	}
	cronCron, cleanup2, err := cron.NewCron(option)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	commandsOptions := commands.Options{
		Commands:     yamlCommands,
		Session:      discordgoSession,
		DiscordCfg:   discordConfig,
		Archive:      archiveArchive,
		Credits:      creditsCredits,
		DontPingMods: dontPingMods,
		GoogleIt:     googleIt,
		Reference:    referenceReference,
		Solved:       solvedSolved,
	}
	commandsCommands, err := commands.NewCommands(commandsOptions)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	appOptions := app.Options{
		Bot:      botBot,
		Session:  sessionSession,
		Handler:  handlerHandler,
		Cron:     cronCron,
		Commands: commandsCommands,
	}
	appApp := app.NewApp(appOptions)
	return appApp, func() {
		cleanup2()
		cleanup()
	}, nil
}

var (
	_wirePathValue = yaml.Path("config.yml")
)
