// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/nestjs-discord/utility-bot/app"
	"github.com/nestjs-discord/utility-bot/bot"
	"github.com/nestjs-discord/utility-bot/bot/antispam"
	"github.com/nestjs-discord/utility-bot/bot/auto_mod"
	"github.com/nestjs-discord/utility-bot/bot/commands"
	"github.com/nestjs-discord/utility-bot/bot/commands/archive"
	"github.com/nestjs-discord/utility-bot/bot/commands/credits"
	"github.com/nestjs-discord/utility-bot/bot/commands/dont_ping_mods"
	"github.com/nestjs-discord/utility-bot/bot/commands/google_it"
	"github.com/nestjs-discord/utility-bot/bot/commands/reference"
	"github.com/nestjs-discord/utility-bot/bot/commands/solved"
	"github.com/nestjs-discord/utility-bot/bot/cron"
	"github.com/nestjs-discord/utility-bot/bot/forms"
	"github.com/nestjs-discord/utility-bot/bot/handler"
	"github.com/nestjs-discord/utility-bot/bot/handler/interaction"
	"github.com/nestjs-discord/utility-bot/bot/markdown"
	"github.com/nestjs-discord/utility-bot/bot/moderators"
	"github.com/nestjs-discord/utility-bot/bot/rate_limit"
	"github.com/nestjs-discord/utility-bot/bot/session"
	"github.com/nestjs-discord/utility-bot/bot/status"
	"github.com/nestjs-discord/utility-bot/infra/config/env"
	"github.com/nestjs-discord/utility-bot/infra/config/yaml"
	"github.com/nestjs-discord/utility-bot/infra/logger"
)

// Injectors from wire.go:

func InitializeApp() (*app.App, func(), error) {
	discordConfig, err := env.NewDiscordConfig()
	if err != nil {
		return nil, nil, err
	}
	stage, err := env.NewStageConfig()
	if err != nil {
		return nil, nil, err
	}
	loggerLogger, err := logger.NewLogger(stage)
	if err != nil {
		return nil, nil, err
	}
	botBot, cleanup, err := bot.NewBot(discordConfig, loggerLogger)
	if err != nil {
		return nil, nil, err
	}
	sessionSession := bot.ProvideSession(botBot)
	path := _wirePathValue
	config, err := yaml.NewConfig(path)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	yamlForms := yaml.NewForms(config)
	discordgoSession := session.ProvideSession(sessionSession)
	guildId := env.ProvideGuildId(discordConfig)
	autoMod, err := auto_mod.NewAutoMod(discordgoSession, guildId)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	yamlCommands := yaml.NewCommands(config)
	markdownMarkdown := markdown.NewMarkdown(yamlCommands)
	formsForms, err := forms.NewForms(yamlForms, autoMod, markdownMarkdown, discordgoSession)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	yamlModerators := yaml.NewModerators(config)
	moderatorsModerators, err := moderators.NewModerators(yamlModerators)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	rateLimit := yaml.NewRateLimit(config)
	rate_limitRateLimit := rate_limit.NewRateLimit(rateLimit, moderatorsModerators)
	archiveCommand := yaml.NewArchiveCommand(config)
	archiveArchive := archive.NewArchive(archiveCommand, moderatorsModerators)
	creditsCredits := credits.NewCredits()
	googleIt := google_it.NewGoogleIt()
	referenceReference := reference.NewReference()
	solvedCommand := yaml.NewSolvedCommand(config)
	solvedSolved := solved.NewSolved(solvedCommand, moderatorsModerators)
	dontPingMods := dont_ping_mods.NewDontPingMods(moderatorsModerators)
	interactionHandler := interaction.NewInteractionHandler(formsForms, moderatorsModerators, rate_limitRateLimit, markdownMarkdown, archiveArchive, creditsCredits, googleIt, referenceReference, solvedSolved, dontPingMods)
	yamlAntispam := yaml.NewAntispam(config)
	antispamAntispam, err := antispam.NewAntispam(yamlAntispam, moderatorsModerators)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	handlerHandler := handler.NewHandler(interactionHandler, antispamAntispam, formsForms, markdownMarkdown, moderatorsModerators)
	statusStatus := status.NewStatus(discordgoSession)
	option := cron.Option{
		AutoMod: autoMod,
		Status:  statusStatus,
	}
	cronCron, cleanup2, err := cron.NewCron(option)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	commandsCommands, err := commands.NewCommands(discordgoSession, discordConfig, yamlCommands, archiveArchive, creditsCredits, dontPingMods, googleIt, referenceReference, solvedSolved)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	appApp := app.NewApp(botBot, sessionSession, handlerHandler, cronCron, commandsCommands)
	return appApp, func() {
		cleanup2()
		cleanup()
	}, nil
}

var (
	_wirePathValue = yaml.Path("config.yml")
)
