// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/nestjs-discord/utility-bot/bot"
	"github.com/nestjs-discord/utility-bot/bot/antispam"
	"github.com/nestjs-discord/utility-bot/bot/commands"
	"github.com/nestjs-discord/utility-bot/bot/commands/archive"
	"github.com/nestjs-discord/utility-bot/bot/commands/dont_ping_mods"
	"github.com/nestjs-discord/utility-bot/bot/commands/google_it"
	"github.com/nestjs-discord/utility-bot/bot/commands/reference"
	"github.com/nestjs-discord/utility-bot/bot/commands/solved"
	"github.com/nestjs-discord/utility-bot/bot/forms"
	"github.com/nestjs-discord/utility-bot/bot/handler"
	"github.com/nestjs-discord/utility-bot/bot/handler/interaction"
	"github.com/nestjs-discord/utility-bot/bot/markdown"
	"github.com/nestjs-discord/utility-bot/bot/moderators"
	"github.com/nestjs-discord/utility-bot/bot/rate_limit"
	"github.com/nestjs-discord/utility-bot/bot/session"
	"github.com/nestjs-discord/utility-bot/infra/config/env"
	"github.com/nestjs-discord/utility-bot/infra/config/yaml"
	"github.com/nestjs-discord/utility-bot/infra/logger"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	discordConfig, err := env.NewDiscordConfig()
	if err != nil {
		return nil, err
	}
	stage, err := env.NewStageConfig()
	if err != nil {
		return nil, err
	}
	loggerLogger, err := logger.Initialize(stage)
	if err != nil {
		return nil, err
	}
	botBot, err := bot.NewBot(discordConfig, loggerLogger)
	if err != nil {
		return nil, err
	}
	sessionSession := bot.ProvideSession(botBot)
	path := _wirePathValue
	config, err := yaml.NewConfig(path)
	if err != nil {
		return nil, err
	}
	yamlForms := yaml.NewForms(config)
	yamlCommands := yaml.NewCommands(config)
	markdownMarkdown := markdown.NewMarkdown(yamlCommands)
	discordgoSession := session.ProvideSession(sessionSession)
	formsForms, err := forms.NewForms(yamlForms, markdownMarkdown, discordgoSession)
	if err != nil {
		return nil, err
	}
	yamlModerators := yaml.NewModerators(config)
	moderatorsModerators, err := moderators.NewModerators(yamlModerators)
	if err != nil {
		return nil, err
	}
	rateLimit := yaml.NewRateLimit(config)
	rate_limitRateLimit := rate_limit.NewRateLimit(rateLimit, moderatorsModerators)
	archiveArchive := archive.New(moderatorsModerators)
	googleIt := google_it.NewGoogleIt()
	referenceReference := reference.New()
	solvedSolved := solved.New(moderatorsModerators)
	dontPingMods := dont_ping_mods.NewDontPingMods(moderatorsModerators)
	interactionHandler := interaction.NewHandler(formsForms, moderatorsModerators, rate_limitRateLimit, markdownMarkdown, archiveArchive, googleIt, referenceReference, solvedSolved, dontPingMods)
	yamlAntispam := yaml.NewAntispam(config)
	antispamAntispam, err := antispam.NewAntispam(yamlAntispam, moderatorsModerators)
	if err != nil {
		return nil, err
	}
	handlerHandler := handler.NewHandler(interactionHandler, antispamAntispam, formsForms, markdownMarkdown, moderatorsModerators)
	commandsCommands, err := commands.NewCommands(discordgoSession, discordConfig, yamlCommands, archiveArchive, googleIt, referenceReference, solvedSolved)
	if err != nil {
		return nil, err
	}
	app := NewApp(botBot, sessionSession, handlerHandler, commandsCommands)
	return app, nil
}

var (
	_wirePathValue = yaml.Path("config.yml")
)
